"""Central domain constants for the backend."""

from pathlib import Path

API_PREFIX = "/api"

DEFAULT_PLUGIN_DIR = Path(__file__).resolve().parents[1] / "plugins"
DEFAULT_DATA_DIR = Path(__file__).resolve().parents[1] / "data"
DEFAULT_STATE_PATH = DEFAULT_DATA_DIR / "app_state.json"
DEFAULT_MODEL_STORAGE_DIR = DEFAULT_DATA_DIR / "models"
DEFAULT_GENERATION_ARTIFACT_DIR = DEFAULT_DATA_DIR / "generation-artifacts"
PROJECT_ROOT = Path(__file__).resolve().parents[3]
LOCAL_FLUX_FILL_DIFFUSERS_DIR = PROJECT_ROOT / "models" / "diffusers" / "FLUX.1-Fill-dev"
LOCAL_FLUX_FILL_FP8_TRANSFORMER = (
    PROJECT_ROOT / "data" / "models" / "fluxFillFP8_v10.safetensors"
)
PERSISTENCE_VERSION = 1
PERSISTENCE_MAX_MODEL_LOADS = 30
PERSISTENCE_MAX_PROJECTS = 60
PERSISTENCE_MAX_GENERATIONS = 120

DEFAULT_DEVICE = "auto"
DEFAULT_DTYPE = "auto"
DEFAULT_WIDTH = 768
DEFAULT_HEIGHT = 768
SDXL_MIN_PROCESS_SIZE = 1024
DEFAULT_STEPS = 28
DEFAULT_GUIDANCE = 7.5
DEFAULT_STRENGTH = 1.0
DEFAULT_SAMPLE_COUNT = 1
DEFAULT_MASK_BLUR = 0
DEFAULT_MASK_CROP_PADDING = 32
DEFAULT_OUTPAINT_MAX_WIDTH = 1536
DEFAULT_OUTPAINT_MAX_HEIGHT = 1024
LIGHTING_CONTEXT_TONE_RAMP = 64
LIGHTING_CONTEXT_TONE_STRENGTH = 0.85

PROGRESS_STARTED = 0.02
PROGRESS_FINISHED = 1.0

WHITE_MASK_THRESHOLD = 128
COMPOSITION_FEATHER_RADIUS = 12
ORIGINAL_RESTORE_FEATHER_RADIUS = 3

DATA_URL_SEPARATOR = ","
PNG_MEDIA_TYPE = "image/png"

ADAPTER_SD15_INPAINT = "sd15-inpaint"
ADAPTER_SD15_CONTROLNET_INPAINT = "sd15-controlnet-inpaint"
ADAPTER_SD15_IMG2IMG = "sd15-img2img"
ADAPTER_SDXL_INPAINT = "sdxl-inpaint"
ADAPTER_SDXL_CONTROLNET_INPAINT = "sdxl-controlnet-inpaint"
ADAPTER_SDXL_CONTROLNET_UNION_INPAINT = "sdxl-controlnet-union-inpaint"
ADAPTER_SDXL_IMG2IMG = "sdxl-img2img"
ADAPTER_SDXL_FILL_CONTROLNET_UNION = "sdxl-fill-controlnet-union"
ADAPTER_FLUX_FILL = "flux-fill"
ADAPTER_FLUX_FILL_FP8 = "flux-fill-fp8"
ADAPTER_CHROMA_INPAINT = "chroma-inpaint"
ADAPTER_ZIMAGE_INPAINT = "zimage-inpaint"

MODEL_SD15 = "stable-diffusion-v1-5/stable-diffusion-v1-5"
MODEL_SD15_INPAINT = "stable-diffusion-v1-5/stable-diffusion-inpainting"
MODEL_SD15_CONTROLNET_SCRIBBLE = "lllyasviel/control_v11p_sd15_scribble"
MODEL_SD15_CONTROLNET_TILE = "lllyasviel/control_v11f1e_sd15_tile"
MODEL_SD2_INPAINT = "stabilityai/stable-diffusion-2-inpainting"
MODEL_SDXL = "stabilityai/stable-diffusion-xl-base-1.0"
MODEL_SDXL_INPAINT = "diffusers/stable-diffusion-xl-1.0-inpainting-0.1"
MODEL_SDXL_CONTROLNET_SCRIBBLE = "xinsir/controlnet-scribble-sdxl-1.0"
MODEL_SDXL_CONTROLNET_TILE = "xinsir/controlnet-tile-sdxl-1.0"
MODEL_SDXL_FILL_CONTROLNET_UNION = "SG161222/RealVisXL_V5.0_Lightning"
MODEL_SDXL_FILL_CONTROLNET_UNION_CONTROLNET = "xinsir/controlnet-union-sdxl-1.0"
MODEL_SDXL_FILL_CONTROLNET_UNION_VAE = "madebyollin/sdxl-vae-fp16-fix"
MODEL_SDXL_FILL_CONTROLNET_UNION_CONTROLNET_CONFIG = "config_promax.json"
MODEL_SDXL_FILL_CONTROLNET_UNION_CONTROLNET_WEIGHTS = "diffusion_pytorch_model_promax.safetensors"
MODEL_FLUX_FILL = "black-forest-labs/FLUX.1-Fill-dev"
MODEL_CHROMA_INPAINT = "lodestones/Chroma1-HD"
MODEL_ZIMAGE_INPAINT = "Tongyi-MAI/Z-Image-Turbo"

DEFAULT_FLUX_STEPS = 50
DEFAULT_FLUX_GUIDANCE = 30.0
DEFAULT_CHROMA_STEPS = 28
DEFAULT_CHROMA_GUIDANCE = 7.0
DEFAULT_CHROMA_STRENGTH = 0.6
DEFAULT_ZIMAGE_STEPS = 9
DEFAULT_ZIMAGE_GUIDANCE = 0.0
DEFAULT_CONTROLNET_CONDITIONING_SCALE = 0.75
DEFAULT_CONTROL_GUIDANCE_START = 0.0
DEFAULT_CONTROL_GUIDANCE_END = 1.0
FLUX_MAX_SEQUENCE_LENGTH = 512
CHROMA_MAX_SEQUENCE_LENGTH = 256
ZIMAGE_MAX_SEQUENCE_LENGTH = 512

FAMILY_SD15 = "stable-diffusion-1.5"
FAMILY_SD2 = "stable-diffusion-2"
FAMILY_SDXL = "stable-diffusion-xl"
FAMILY_FLUX = "flux"
FAMILY_CHROMA = "chroma"
FAMILY_ZIMAGE = "z-image"
FAMILY_COMFYUI = "comfyui"

SCHEDULER_AUTO = "auto"
SCHEDULER_DPM_SOLVER = "dpmpp_2m"
SCHEDULER_EULER = "euler"
SCHEDULER_DDIM = "ddim"
SCHEDULER_LMS = "lms"

FILL_TRANSPARENT = "transparent"
FILL_PATCHMATCH = "patchmatch"
FILL_EDGE_EXTEND = "edge_pad"
FILL_GAUSSIAN_NOISE = "gaussian"
FILL_PERLIN_NOISE = "perlin"
FILL_OPENCV_TELEA = "cv2_telea"
FILL_OPENCV_NS = "cv2_ns"

LEGACY_FILL_EDGE_EXTEND = "edge_extend"
LEGACY_FILL_GAUSSIAN_NOISE = "gaussian_noise"
LEGACY_FILL_PERLIN_NOISE = "perlin_noise"
LEGACY_FILL_OPENCV_TELEA = "opencv_telea"
LEGACY_FILL_OPENCV_NS = "opencv_ns"

INPAINT_AREA_WHOLE_SELECTION = "whole_selection"
INPAINT_AREA_ONLY_MASKED = "only_masked"

RESULT_MODE_GENERATED_SELECTION = "generated_selection"
RESULT_MODE_PRESERVE_KNOWN = "preserve_known"
RESULT_MODE_FEATHER_KNOWN = "feather_known"
RESULT_MODE_RESTORE_ORIGINAL_SOFT = "restore_original_soft"
OUTPAINT_STRATEGY_HF_SPACE_FILL = "hf_space_fill"
HF_SPACE_FILL_SIZE_MULTIPLE = 8

GENERATION_MODE_OUTPAINT = "outpaint"
GENERATION_MODE_INPAINT = "inpaint"

CONDITIONING_TYPE_SCRIBBLE = "scribble"
CONDITIONING_TYPE_COLOR = "color"

JOB_QUEUED = "queued"
JOB_RUNNING = "running"
JOB_SUCCEEDED = "succeeded"
JOB_FAILED = "failed"
JOB_CANCELLED = "cancelled"

EVENT_JOB_UPDATE = "job.update"
EVENT_JOB_DONE = "job.done"
EVENT_JOB_ERROR = "job.error"
EVENT_JOB_CANCELLED = "job.cancelled"

ERROR_ADAPTER_NOT_FOUND = "ADAPTER_NOT_FOUND"
ERROR_MODEL_NOT_LOADED = "MODEL_NOT_LOADED"
ERROR_MODEL_LOAD_CANCELLED = "MODEL_LOAD_CANCELLED"
ERROR_MODEL_LOAD_FAILED = "MODEL_LOAD_FAILED"
ERROR_MODEL_LOAD_IN_PROGRESS = "MODEL_LOAD_IN_PROGRESS"
ERROR_MODEL_DOWNLOAD_FAILED = "MODEL_DOWNLOAD_FAILED"
ERROR_GENERATION_FAILED = "GENERATION_FAILED"
ERROR_INVALID_GENERATION_PARAMETERS = "INVALID_GENERATION_PARAMETERS"
ERROR_JOB_NOT_FOUND = "JOB_NOT_FOUND"
ERROR_JOB_NOT_FINISHED = "JOB_NOT_FINISHED"
ERROR_INVALID_IMAGE = "INVALID_IMAGE"
ERROR_PLUGIN_LOAD_FAILED = "PLUGIN_LOAD_FAILED"
ERROR_PLUGIN_NOT_FOUND = "PLUGIN_NOT_FOUND"
ERROR_PLUGIN_ACTION_NOT_FOUND = "PLUGIN_ACTION_NOT_FOUND"
ERROR_PLUGIN_ACTION_FAILED = "PLUGIN_ACTION_FAILED"
ERROR_UNSUPPORTED_OPERATION = "UNSUPPORTED_OPERATION"
ERROR_CANCEL_UNSUPPORTED = "CANCEL_UNSUPPORTED"

CONTROL_TEXT = "text"
CONTROL_TEXTAREA = "textarea"
CONTROL_NUMBER = "number"
CONTROL_SLIDER = "slider"
CONTROL_SELECT = "select"
CONTROL_SWITCH = "switch"

CONTROL_SECTION_BASIC = "basic"
CONTROL_SECTION_ADVANCED = "advanced"
CONTROL_SECTION_RUNTIME = "runtime"
CONTROL_SECTION_EXTENSIONS = "extensions"

POSTPROCESSOR_CATEGORY_GENERATION = "generation"
POSTPROCESSOR_CATEGORY_CORRECTION = "correction"
POSTPROCESSOR_CATEGORY_RESULT_REFINE = "result_refine"
DEFAULT_POSTPROCESSOR_ORDER = 100

PLUGIN_ACTION_MENU_SELECTION = "selection"
PLUGIN_TOOL_TARGET_FRAME = "frame"
PLUGIN_TOOL_TARGET_IMAGE = "image"
PLUGIN_TOOL_TARGET_CANVAS = "canvas"

MODEL_SOURCE_HUB = "hub"
MODEL_SOURCE_LOCAL_FOLDER = "local_folder"
MODEL_SOURCE_SINGLE_FILE = "single_file"
MODEL_SOURCE_DIRECT_URL = "direct_url"

MODEL_SOURCE_FIELD_MODEL_ID = "model_id"
MODEL_SOURCE_FIELD_LOCAL_PATH = "local_path"
MODEL_SOURCE_FIELD_SINGLE_FILE_PATH = "single_file_path"
MODEL_SOURCE_FIELD_MODEL_URL = "model_url"

ALL_SCHEDULERS = [
    SCHEDULER_AUTO,
    SCHEDULER_DPM_SOLVER,
    SCHEDULER_EULER,
    SCHEDULER_DDIM,
    SCHEDULER_LMS,
]
